<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [1]:
# Your code here
# print() is one of the internal function in python
# 2 ways to create functions: 'named' and 'anonymous'

def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [2]:
greeting("Super Man")

'Hello Super Man!'

In [3]:
greeting(name="Super Man")

# function's name is 'greeting'
# accepts single argument called 'name'

'Hello Super Man!'

In [4]:
# 'def' with colon (:) and indentation
# 'return' to get return value as output

greet = greeting(name = 'Super Man')
print(greet)

Hello Super Man!


In [5]:
print(greeting(name = 'Super Man'))

Hello Super Man!


In [20]:
# 'return' can only be used within a function
# eg: list and returns max, min and mean

def basic_stats(numbers):
    np_numbers = np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

print(f"The answer is {list_min, list_max, list_mean}")

The answer is (1, 5, 3.0)


### 1.2 Named functions that don’t return

In [ ]:
# Your code here
# function may not return anything
# eg: print() does not return a value

### 1.3 Anonymous functions

In [21]:
# Your code here
# anonymous or 'lambda' functions are suitable one-liners
# examples accept single argument termed 'name'

my_short_function = lambda name: f"Hello {name}!"

In [22]:
my_short_function(name = "Super Man")

# 'lambda' always return value of last statement

'Hello Super Man!'

In [27]:
# sorting a 2D list by using 'sorted()' function
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [25]:
numbers=[[4, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [9, 0, 10],
         [0, 9, 19],
         [1, 8, 18],
         [2, 7, 17],
         [3, 6, 16]]

sorted(numbers)                         # Sort according to key
                                        # regardless of the order

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 0, 10],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [32]:
# sorting based on first element of sub-lists
# criteria requires a specific 'key'
# lambda function

numbers=[[4, 5, 15],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [9, 0, 10],
         [0, 9, 19],
         [1, 8, 18],
         [2, 7, 17],
         [3, 6, 16]]

sorted(numbers, key = lambda x: x[1])     # sort by comparing custom key
                                          # that uses 2nd element
                                          # refer to table in storing data (good)
                                          # x[1] slices the second element
                                          # python starts first element from 0
# lambda expresses the argument
# 

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [31]:
numbers=[[4, 5, 15],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [9, 0, 10],
         [0, 9, 19],
         [1, 8, 18],
         [2, 7, 17],
         [3, 6, 16]]

sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [35]:
# Your code here
# giving argument a default value

def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
print(greeting())

Hello no one!


In [36]:
# running function without argument
greeting()

'Hello no one!'

In [37]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [39]:
# print() accept other arguments
# also optional with default values
# to specify them:

print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')      # sep = seperation?
#> I---am---Batman!

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

In [ ]:
# Your code here
# abstraction of details: putting solution into chunks (functions)
# reusability of code: encapsulate code in function
# maintainability of code: make changes in one place

### 2.2 A word of caution

In [ ]:
# Your code here
# don't do too many arguments
# don't overuse

## Exercise 1 :  Do you know why?

In [32]:
# Your solution here
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'
print(greeting('Batman'))
print(greeting('Kiwi'))

Hello Batman! So, nice to meet you!
Hello Kiwi!


In [47]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
        return f'Hello {name}!'
print(greeting('Batman'))
print(greeting('Kiwi'))

Hello Batman! So, nice to meet you!
None


`else` statement is an optional statement. Hence when the condition defined here, which is `if name == 'Batman'`, is not met, the code will automatically ignores the `return 'Hello Batman! So, nice to meet you!'` and runs `return f'Hello {name}!'` instead. This is so as there is an indention in the first cell for `return f'Hello {name}!'` such that it replaces the `else` in that position. As compared to the second cell, when `return f'Hello {name}!'` is on the same indention as `return 'Hello Batman! So, nice to meet you!'`, there is no else alternative and the output is shown as `None`.

## Exercise 2 :  Calculator functions

In [5]:
# Your solution here
def add(x, y): 
    return x + y
print(add(1, 2))

3


In [6]:
def subtract(x, y):
    return x - y
print(subtract(2, 1))

1


In [7]:
def multiply(x, y):
    return x * y
print(multiply(1, 2))

2


In [8]:
# add an 'if' condition to admonish division user by zero
# exit() or quit() to force stop python

def divide(x, y):
    if np.all(y < 0):
        return exit()
    return x / y

In [9]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

add(x, y)

array([100, 100, 100, 100, 100])

In [10]:
subtract(x, y)

array([-28, -32, -12,  52, -46])

In [12]:
multiply(x, y)

array([2304, 2244, 2464, 1824, 1971])

In [1]:
import numpy as np

x = np.array([36, 34, 44, 76, 27])
y = np.array([64, 66, 56, 24, 73])

def divide(x, y):
    if np.all(y < 0):
        return exit()
    return x / y

divide(x, y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

In [9]:
x = 2
y = 2

def divide(x, y):
    print(isinstance(x, (int, float, list)))
    print(isinstance(y, (int, float, list)))
    if y == 0:
        return exit()
    return x / y
print(divide(x, y))


# x.all() or x.any() works for arrays (and list?)
# doesn't work if u define x and y by a single element

# using isinstance() to check
# such that it can accept integers, floats and arrays

True
True
1.0


## Exercise 3 :  max_info() with NumPy

In [18]:
# Your solution here
def max_info(numbers):
    return f'The number is {np.max(numbers)} located at index {np.argmax(numbers)} of this list.'

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
print(max_info(numbers))

The number is 83 located at index 2 of this list.
