<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [1]:
# Your code here
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

- **subsetting** means to 'select'
- **indexing** refers to selecting one element
- **slicing** refers to selecting a range of elements

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

### 1.2 Subsetting by masking (Arrays only)

In [3]:
# Your code here
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [4]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [5]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [6]:
np_array[~(np_array > 3)]                         # '~' means 'NOT'

array([1, 2, 3])

In [7]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

array([4, 5, 6, 7])

In [8]:
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [9]:
# Your code here
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [10]:
# example 1
py_list_2d[3]        # What is at position 4 (index 3)?

[4, 'D']

In [11]:
# example 2
py_list_2d[3][0]     # FIRST element at position 4 (index 3)

4

In [12]:
# example 3
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [13]:
# example 4
py_list_2d[:3][0]

[1, 'A']

In [14]:
# example 5
py_list_2d[3:6][0]

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [15]:
# Your code here
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [16]:
# example 1
np_array_2d[3]       # What is at position 4 (index 3)?

array(['4', 'D'], dtype='<U11')

In [17]:
# example 2
np_array_2d[3, 0]    # FIRST element at position 4 (index 3)

'4'

In [18]:
# example 3
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [19]:
# example 4
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [20]:
# example 5
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

In [21]:
# example 6
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [22]:
# Your code here
# example 1
x=[1]*10
x               # I am lazy to type print()
                # Let Jupyter do the hard work.

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [23]:
# example 2
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [24]:
# example 3
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [25]:
# example 4
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [26]:
# example 5
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [27]:
# example 6
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [28]:
# Your code here
a=(1, 2, 3)     # Define tuple

In [29]:
# accessing data
print(a[0])    # Access data

1


In [30]:
# The following will NOT work
a[0]=-1
a[0] += [10]

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [32]:
# Your code here
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [34]:
# corret way of doing
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

# Your solution here
|**Term**|**Brief description**|
|:---|---:|
|Subsetting|*selecting data*|
|Indexing|*selecting one element in a list or array*|
|Slicing|*selecting a range of elements*|
|Masking|*choosing specific data to be shown*|


## Exercise 2 :  Show me the ‘odd’ letters

In [80]:
# Your solution here
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

#np_array_2d[:, 0]
#np_array_2d[:, 0].astype(int)
#np_array_2d[:, 0].astype(int)%2
#np_array_2d[:, 0].astype(int)%2 == 1
#np_array_2d[np_array_2d[:, 0].astype(int)%2 == 1, 1]

mask = np_array_2d[:, 0].astype(int)%2 == 1
np_array_2d[mask, 1]
# np_array[np_array_2d[:, 0].astype(int)%2 == 1]

#array = np_array_2d[:, 0].astype(int)%2 == 1
#np_array[array]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')